name: Keep Alive Streamlit

on:
  schedule:
    - cron: "*/20 * * * *"   # tiap 20 menit (UTC)
  workflow_dispatch:          # bisa run manual dari tab Actions

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl app (wake ping)
        run: |
          URL="https://stc-gasvision.streamlit.app/?utm=keepalive"
          UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124 Safari/537.36"
          for i in 1 2; do
            CODE=$(curl -sS -o /dev/null -w "%{http_code}" -L -A "$UA" "$URL")
            echo "Hit #$i -> HTTP $CODE"
            sleep 10
          done
